name: Diff proposed configuration changes (PR opened)

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build firewall-commit binary
        run: |
          cd scripts
          go mod init github.com/cdot65/pan-terraform-github-actions
          go mod tidy
          go build -o firewall-commit firewall-commit.go

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.0

      - name: Terraform Init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd san-vfw-01
          terraform init -backend-config="bucket=${{ secrets.BACKEND_BUCKET }}"
          terraform workspace new san-vfw-01

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform state update
        run: terraform state pull

      - name: Terraform Plan
        working-directory: san-vfw-01/
        run: terraform plan | sed 's/\x1b\[[0-9;]*m//g' > config_diff.txt
        env:
          TF_VAR_panos_username: ${{ secrets.PANOS_USERNAME }}
          TF_VAR_panos_password: ${{ secrets.PANOS_PASSWORD }}

      - name: Upload config_diff.txt
        uses: actions/upload-artifact@v2
        with:
          name: config_diff
          path: san-vfw-01/config_diff.txt

  post_plan_comment:
    runs-on: self-hosted
    needs: deploy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download config_diff.txt
        uses: actions/download-artifact@v2
        with:
          name: config_diff
          path: san-vfw-01/

      - name: Post Plan Result as Comment
        uses: actions/github-script@v5
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            const config_diff = fs.readFileSync(path.join(process.env.GITHUB_WORKSPACE, 'san-vfw-01', 'config_diff.txt'), 'utf8');
            const pr_id = context.issue.number;
            const comment_body = `\`\`\`
                ${config_diff}
            \`\`\``;
            await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr_id,
                body: comment_body
            });
          github-token: ${{ secrets.PAT }}
